-- Table: public.usuario

-- DROP TABLE IF EXISTS public.usuario;

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default",
    login character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    semestre integer,
    curso_id bigint NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT email_uni UNIQUE (email),
    CONSTRAINT login_uni UNIQUE (login),
    CONSTRAINT usuario_curso_id FOREIGN KEY (curso_id)
        REFERENCES public.curso (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuario
    OWNER to postgres;


--senha = usuario
INSERT INTO public.usuario(email, login, password, semestre, curso_id) VALUES
('usuario@email.com', 'usuario', '$2a$10$sQnC73si3NoOPV4iSJX0EOmhcVUvIgotrcd17D0xpbR4PfkJYCptu', 1, 1),
('usuario2@email.com', 'usuario2', '$2a$10$sQnC73si3NoOPV4iSJX0EOmhcVUvIgotrcd17D0xpbR4PfkJYCptu', 2, 1);