-- Table: public.curso

-- DROP TABLE IF EXISTS public.curso;

CREATE TABLE IF NOT EXISTS public.curso
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default",
    sigla character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT curso_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.curso
    OWNER to postgres;


INSERT INTO public.curso (nome, sigla) VALUES
('Analise e desenvolvimento de sistemas', 'ADS');
