-- Table: public.semestre

-- DROP TABLE IF EXISTS public.semestre;

-- Table: public.semestre

-- DROP TABLE IF EXISTS public.semestre;

CREATE TABLE IF NOT EXISTS public.semestre
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default",
    curso_id bigint NOT NULL,
    CONSTRAINT semestre_pkey PRIMARY KEY (id),
    CONSTRAINT semestre_curso_id FOREIGN KEY (curso_id)
        REFERENCES public.curso (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.semestre
    OWNER to postgres;


INSERT INTO public.semestre (nome, curso_id) VALUES
('1 Semestre', 1),
('2 Semestre', 1),
('3 Semestre', 1),
('4 Semestre', 1),
('5 Semestre', 1),
('6 Semestre', 1);