-- Table: public.tema

-- DROP TABLE IF EXISTS public.tema;

CREATE TABLE IF NOT EXISTS public.tema
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default",
    excluido boolean NOT NULL,
    titulo character varying(255) COLLATE pg_catalog."default",
    curso_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT tema_pkey PRIMARY KEY (id),
    CONSTRAINT tema_usuario_id FOREIGN KEY (usuario_id)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tema_curso_id FOREIGN KEY (curso_id)
        REFERENCES public.curso (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tema
    OWNER to postgres;


INSERT INTO public.tema (descricao, excluido, titulo, curso_id, usuario_id) VALUES
('Sistema para administrar uma padaria', false, 'Padaria', 1, 1),
('Sistema para administrar uma barbearia', false, 'Barbearia', 1, 2),
('Sistema para administrar um mercado', false, 'Mercado', 1, 1),
('Sistema para administrar uma papelaria', false, 'Papelaria', 1, 1);