-- Table: public.disciplina

-- DROP TABLE IF EXISTS public.disciplina;

CREATE TABLE IF NOT EXISTS public.disciplina
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default",
    sigla character varying(255) COLLATE pg_catalog."default",
    curso_id bigint NOT NULL,
    CONSTRAINT disciplina_pkey PRIMARY KEY (id),
    CONSTRAINT disciplina_curso_id FOREIGN KEY (curso_id)
        REFERENCES public.curso (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.disciplina
    OWNER to postgres;


INSERT INTO public.disciplina (nome, sigla, curso_id) VALUES
('ILM-001', 'Programação em Microinformática', 1),
('IAL-002', 'Algoritmos e Lógica de Programação', 1),
('IHW-100', 'Laboratório de Hardware', 1),
('IAC-001', 'Arquitetura e Organização de Computadores', 1),
('AAG-001', 'Administração Geral', 1),
('MMD-001', 'Matemática Discreta', 1),
('LIN-100', 'Inglês I', 1),
('IES-100', 'Engenharia de Software I', 1),
('ILP-010', 'Linguagem de Programação', 1),
('ISI-002', 'Sistemas de Informação', 1),
('CCG-001 ', 'Contabilidade', 1),
('MCA-002', 'Cálculo', 1),
('LPO-001', 'Comunicação e Expressão', 1);
